### ISSUE TITLE
Accessing the original movie texture

### ISSUE THREAD

**Issue by rsodre** [resolume/ffgl#8]
The host (Resolume) renders a frame using the original movie texture then passes this frame to the FFGL plugin to work with. Is there any way to access or replace the input texture for the original movie texture?

Example: If I want to make an effect that is a "window" into a VR video. The source video is 4096x2048, and my composition is 1920x1080. The only way to access all the pixels from the movie is to stretch it to fill the composition, highly reducing reducing my original pixels from my VR video.

Another example: I have an 8K movie and a 1080 composition. I want to crop and zoom into the 8K movie. Having to stretch it to composition will completely ruin the original 8K resolution.

**Comment by jorisdejong** [comment]
This is a question for the host application. 

In the case of Resolume, you can do this by placing the effect before the Transform.

**Comment by rsodre** [comment]
> In the case of Resolume, you can do this by placing the effect before the Transform.

But then the output frame would be same size as the input texture, right? I would process an 8K frame to later rescale down to 1080, a lot of unnecessary pixels rendering.

The best scenario would to have the full 8K input texture, rendering the effect to the composition frame size. Is that possible on Resolume?

**Comment by jorisdejong** [comment]
If I wanted to write an effect like this, I'd start by comparing the input texture's resolution to the viewport's resolution, and seeing how those values are affected by where the effect is in the render chain.
If the viewport set by the host doesn't give me the values I need, I'd try setting it myself.

**Comment by rsodre** [comment]
As far as I could check, the input texture and frame size are always the same, equal to the composition size. I tried your suggestion of placing the effect before transform, and the frame size is still the composition size, so I still have to stretch the movie to the layer and lose valuable pixels.

I would suggest to add a new special blend mode "Texture bypass" or something. If checked, you send the full texture as input and do not need to pre-render the frame and later blend it with the effect. It will actually save two render passes. If we could turn it on from the FFGL plugin, even better!

That would work as expected on Resolume only, but why not make it better? :) I don't know what's the status of FFGL lib development today, but that could be added as a new feature on the next version specification.

**Comment by jorisdejong** [comment]
Ah yes, in 6 the original texture is only available on the clip pass. Someone just asked a related question on the Resolume forum: http://resolume.com/forum/viewtopic.php?f=12&t=15677

Now, if we were an American company, I'd say that we "value your feedback" and we'll "take your suggestions under consideration". And then never do anything with it. 

I think that's bullshit and prefer treating you as an adult. This is risky because it may look as if I think your idea is stupid and that we're assholes that don't listen to our users. That's not the case, it's a good idea and gets you what you need, almost within the current architecture. 

The truth is, we've got a 1000 great user ideas that we'd like to work on. And this one is just far too specific of a use case. If we look at how many people are using FFGL, and then look at how many people would use this functionality, I'd be surprised if it was more than a handful, and most likely just you.

When we do get the time to do any work on FFGL, I would like to implement that plugins can receive more than one texture, without having to be a blend mode. Then you can reserve a layer that renders at 8K, and pass its input to a plugin rendering somewhere else in the composition. 

But yeah, as it is, we've got our plates pretty full at the moment and updates to expand FFGL are not very high on the priority list.

**Comment by rsodre** [comment]
Sure, I understand. If you need remote help... ;)

Another way to see this feature is as a generator effect, but with the source texture as input.
